[package]
name = "src-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
duckdb = "1.2.2"
arrow = { version = "*", default-features = false, features = ["prettyprint"] }
fxhash = "0.2.1"
